[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.19.3"
quilt_mappings = "1.19.3+build.5"
quilt_loader = "0.18.1-beta.25"

isnrmn = "v1_03"
fabric_asm = "v2.3"
cca = "5.1.0"
mixin_extras = "0.1.1"
trinkets = "3.5.0"
satin = "1.10.0"
quilt_loading_screen = "5.0.0+1.19.3-rc1"
midnightlib = "1.1.0"
emi = "0.5.0+1.19.3"
annotations = "1.0"
quilted_fabric_api = "5.0.0-alpha.7+0.70.0-1.19.3"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

isnrmn = { module = "maven.modrinth:isnrmn", version.ref = "isnrmn" }
fabric_asm = { module = "com.github.Chocohead:Fabric-ASM", version.ref = "fabric_asm"}
cardinal_components_base = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-base", version.ref = "cca" }
cardinal_components_entity = { module = "dev.onyxstudios.cardinal-components-api:cardinal-components-entity", version.ref = "cca" }
mixin_extras = { module = "com.github.LlamaLad7:MixinExtras", version.ref = "mixin_extras" }
trinkets = { module = "dev.emi:trinkets", version.ref = "trinkets" }
quilt_loading_screen = { module = "maven.modrinth:quilt-loading-screen", version.ref = "quilt_loading_screen" }
midnightlib = { module = "maven.modrinth:midnightlib", version.ref = "midnightlib"}
satin = { module = "io.github.ladysnake:satin", version.ref = "satin" }
emi = { module = "dev.emi:emi", version.ref = "emi" }
annotations = { module = "com.demonwav.mcdev:annotations", version.ref = "annotations" }
quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
# [bundles]
# example = ["example-a", "example-b", "example-c"]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "0.12.+" }
